[book]
#title = "Example book"
#author = "John Doe"
description = "The example book covers examples."
language = "zh-Hans"

[build]
build-dir = "book"
create-missing = false

[output.html]
highlight-theme = "github"
site-url = "/rk202511/"
mathjax-support = false
katex-support = true

[output.html.search]
limit-results = 15

[output.html.playground.markdown]
image_directory = "images"

[output.html.playground]
editable = true

[book.preprocessors]
search = { name = "mdbook-search" }
